pipeline {
    agent {
        label 'AGENT-1'

    }
    environment {
        appVersion = ''
        Region = "us-east-1"
        ACC_ID = "968220652823"
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 30, unit: "MINUTES")
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {


                    sh """
                        cd 10-sg
                        terraform init -reconfigure
                    """
                    }
                }
            }
        }
        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                        sh """
                            cd 10-sg
                            terraform plan
                        """

                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds',region: 'us-east-1') {
                    sh """
                        cd 10-sg
                        terraform apply -auto-approve
                    """
                    }
                }
            }
        }
        stage('bastion eks acm') {
            parallel {
                stage('trigger bastion') {
                    steps {
                        script {
                            build job: '20-bastion',
                            propagate: false,
                            wait: false
                        }
                    }
                }
                stage('trigger eks') {
                    steps {
                        script {
                            build job: '80-eks',
                            propagate: false,
                            wait: false
                        }
                    }
                }
                stage('trigger acm') {
                    steps {
                        script {
                            build job: '60-acm',
                            propagate: false,
                            wait: false
                        }
                    }
                }
            }
        }
        stage('trigger alb') {
            steps {
                script {
                    build job: '70-frontendalb',
                    propagate: false,
                    wait: false
                }
            }
        }



    }
    post {
        always {
            echo 'hello'
            deleteDir()

        }
        success {
            echo "successfully completed"
        }
        failure {
            echo "failed dude"
        }
    }
}
