pipeline {
    agent {
        label 'AGENT-1'

    }
    environment {
        appVersion ''
        Region = "us-east-1"
        ACC_ID = "968220652823"
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 30, unit: "MINUTES")
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {


                    sh """
                        cd 20-bastion
                        terraform init -reconfigure
                    """
                    }
                }
            }
        }
        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                        sh """
                            cd 20-bastion
                            terraform plan
                        """

                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds',region: 'us-east-1') {
                    sh """
                        cd 20-bastion
                        teraform apply -auto-approve
                    """
                    }
                }
            }
        }

    }
    post {
        always {
            echo 'hello'
            deleteDir()

        }
        success {
            echo "successfully completed"
        }
        failure {
            echo "failed dude"
        }
    }
}
